version: '3.4'

services:
  rctbot:
    image: rctbot
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rctbot
    env_file: .env
    environment:
      DEPLOYMENT: 0
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  default:
    external:
      name: rctbot
